import React, { Component } from 'react';
import './techItem.scss';

// Array of Tech
const techArray = [
  {
    alt: 'react logo',
    logo: require('./images/logo_react.png'),
    title: 'React',
    description: `React is an incredible tool that assists with the quick and easy creation of interactive UIs.`
  },
  {
    alt: 'javascript logo',
    logo: require('./images/logo_js.png'),
    title: 'JavaScript',
    description: `All my projects make use of JavaScript (ES6+) for interactivity and functionality.`
  },
  {
    alt: 'sass logo',
    logo: require('./images/logo_sass.png'),
    title: 'Sass',
    description: `SASS concepts such as partials, mixins and extend/inheritance are used to keep code modular and maintainable.`
  },
  {
    alt: 'cypress logo',
    logo: require('./images/cypress.png'),
    title: 'Cypress',
    description: `Unit test in Cypress with Cucumber and Gherkin natural language syntax. I've integrated axe-core for automated testing of WCAG accessibility standards.`
  },
  {
    alt: 'terminal logo',
    logo: require('./images/logo_terminal.png'),
    title: 'Bash / NPM / Webpack',
    description: `I create bash scripts to automate repetitive tasks and keep my workflow efficient and productive.`
  },
  {
    alt: 'git logo',
    logo: require('./images/logo_github.png'),
    title: 'Git, GitHub & SVN',
    description: `I use Git or SVN on all projects for version control and code sharing.`
  },
  {
    alt: 'html logo',
    logo: require('./images/logo_html.png'),
    title: 'HTML5',
    description: `HTML gives the page structure; often generated by templating engines like Pug and stylesheets such as XSLT.`
  },
  {
    alt: 'css logo',
    logo: require('./images/logo_css.png'),
    title: 'CSS3',
    description: `Precise and responsive layouts can be created with Flexbox and grid systems such as FoundationXY.`
  },
  {
    alt: 'bootstrap logo',
    logo: require('./images/logo_bootstrap.png'),
    title: 'Bootstrap',
    description: `Bootstrap is a fantastic framework for quickly creating new projects with a clean and consistent layout. Easily modified with CSS to ensure each project is handcrafted and unique!`
  }
];

const techObjects = techArray.map(function(item) {
  return (
    <div className='item'>
      <div className='logo-container'>
        <img className='logo' src={item.logo} alt={item.alt} />
      </div>
      <span className='heading'>{item.title}</span>
      <span className='description'>{item.description}</span>
    </div>
  );
});

export default class TechItem extends Component {
  render() {
    return <div className='items'>{techObjects}</div>;
  }
}
